# name: tests

# on:
#   workflow_dispatch:
#   push:
#     branches-ignore:
#     - 'wip-*'
#     paths-ignore:
#     - 'docs/**'
#   pull_request:
#     branches-ignore:
#     - 'wip-*'
#     paths-ignore:
#     - 'docs/**'

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       max-parallel: 3
#       matrix:
#         python:
#         - version: 2.7
#           toxenv: py27,py27-flask
#         - version: 3.6
#           toxenv: py36,flask,django,py3
#         - version: 3.7
#           toxenv: py37,flask,django,py3
#         - version: 3.8
#           toxenv: py38,flask,django,py3
#         - version: 3.9
#           toxenv: py38,flask,django,py3
#         - version: 3.10
#           toxenv: py38,flask,django,py3
#         - version: 3.11
#           toxenv: py38,flask,django,py3

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{ matrix.python.version }}
#       uses: actions/setup-python@v1.1.1
#       with:
#         python-version: ${{ matrix.python.version }}

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install tox
#         pip install -r requirements-test.txt

#     - name: Test with tox ${{ matrix.python.toxenv }}
#       env:
#         TOXENV: ${{ matrix.python.toxenv }}
#       run: tox

#     - name: Report coverage
#       run: |
#         coverage combine
#         coverage report
#         coverage xml

#     - name: Upload coverage to Codecov  
#       uses: codecov/codecov-action@v1.0.5
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./coverage.xml
#         flags: unittests
#         name: GitHub

name: tests
on:
  push:
    workflow_dispatch:
    branches:
      - master
      - main
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        # TODO: add windows-latest
        os: [ubuntu-latest, macos-latest]
        python:
        - version: 3.7
          toxenv: py37,flask,django,py3
        - version: 3.8
          toxenv: py38,flask,django,py3
        - version: 3.9
          toxenv: py38,flask,django,py3
        - version: 3.10
          toxenv: py38,flask,django,py3
        - version: 3.11
          toxenv: py38,flask,django,py3
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox tox-gh-actions
      - run: pip install -r requirements-test.txt
      - name: Test with tox ${{ matrix.python.toxenv }}
        env:
          TOXENV: ${{ matrix.python.toxenv }}
        run: tox